version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: go_sqlc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sqlc_testdb
    ports:
      - "5432:5432" # Maps container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

